### ISSUE TITLE
Unclear error message for missing newline in the end

### ISSUE THREAD

**Issue by g4s8** [yegor256/xcop#12]
xcop says:
>Invalid XML formatting in ./some-file.xml

if xml file doesn't have newline at the end of file.

It's not easy to understand what is wrong with this file.

**Comment by 0crat** [comment]
@g4s8 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/xcop/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.6`

**Comment by yegor256** [comment]
@g4s8 can you please check version 0.5.6? I believe, it's better now.

**Comment by g4s8** [comment]
@yegor256 now it's much better, thanks

**Comment by 0crat** [comment]
I'm not managing ` yegor256/xcop ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
