### ISSUE TITLE
undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by g4s8** [yegor256/xcop#13]
xcop can fail when running from `Rakefile` with error:
>undefined method `text' for nil:NilClass

see this PR for details: https://github.com/zerocracy/datum/pull/110

If I start `xcop $(find . -path ./.idea -prune -name '*.xml')` command it will finish successfully.
If I remove `'**/*.xml'` from task includes it will finish without errors too.

**Comment by 0crat** [comment]
@g4s8 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/xcop/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.5`

**Comment by yegor256** [comment]
@g4s8 try 0.5.5, it should work fine

**Comment by g4s8** [comment]
@yegor256 thanks, it's working now

**Comment by 0crat** [comment]
I'm not managing ` yegor256/xcop ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
