### ISSUE TITLE
Option to disable color coded output on terminal

### ISSUE THREAD

**Issue by aashraybhandar1** [yegor256/xcop#19]
Is there any way to disable the color coded output that appears on the terminal

**Comment by 0crat** [comment]
@aashraybhandar1 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/xcop/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@aashraybhandar1 there is no such option at the moment, but we can add `--nocolor` option.

**Comment by 0crat** [comment]
Job [#19](https://github.com/yegor256/xcop/issues/19) is now in scope, role is `DEV`

**Comment by aashraybhandar1** [comment]
@yegor256  can I be assigned this issue?

**Comment by yegor256** [comment]
@0crat assign @aashraybhandar1

**Comment by 0crat** [comment]
> @0crat assign @aashraybhandar1  ([here](https://github.com/yegor256/xcop/issues/19#issuecomment-379785363))

@yegor256 The job [#19](https://github.com/yegor256/xcop/issues/19) assigned to @aashraybhandar1[/z](https://www.0crat.com/u/aashraybhandar1), here is [why](https://www.0crat.com/footprint/C3RFVLU72/991510935); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) @aashraybhandar1[/z](https://www.0crat.com/u/aashraybhandar1) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@aashraybhandar1[/z](https://www.0crat.com/u/aashraybhandar1) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @aashraybhandar1[/z](https://www.0crat.com/u/aashraybhandar1) resigned from [#19](https://github.com/yegor256/xcop/issues/19), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@aashraybhandar1 I believe it was fixed in https://github.com/yegor256/xcop/pull/23 and release as 0.6

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c0ff7e3-e0b9-4bc8-930d-80f60a6be371, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.GeneratedMethodAccessor357[-1] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#19](https://github.com/yegor256/xcop/issues/19) is now out of scope

**Comment by aashraybhandar1** [comment]
👍
