### ISSUE TITLE
check for the license in the header

### ISSUE THREAD

**Issue by yegor256** [yegor256/xcop#2]
Let's make it possible to also check for the license in the header.

**Comment by 0crat** [comment]
I'm not managing ` yegor256/xcop ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.

**Comment by yegor256** [comment]
@rultor release, tag is `0.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2`

**Comment by 0crat** [comment]
I'm not managing ` yegor256/xcop ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
