### ISSUE TITLE
absent license causes exception

### ISSUE THREAD

**Issue by yegor256** [yegor256/xcop#20]
```
xcop --fix --license LICENSE $(find . -name '*.xsl')
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/xcop-0.5.7/bin/xcop:57:in `read': No such file or directory @ rb_sysopen - LICENSE (Errno::ENOENT)
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/xcop-0.5.7/bin/xcop:57:in `<top (required)>'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/xcop:22:in `load'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/xcop:22:in `<main>'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Instead, we should say something more meaningful, like "file not found"

**Comment by 0crat** [comment]
I'm not managing `yegor256/xcop` GitHub repository, you have to contact me in Slack first, see [§11](http://datum.zerocracy.com/pages/policy.html#11)

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/xcop/issues/20#issuecomment-357498752))

@yegor256 Job [#20](https://github.com/yegor256/xcop/issues/20) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7000](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-0
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), can't add this XML to 2 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1260544441">
   <created>2018-05-06T05:10:37.151Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:yegor256/xcop#20</param>
      <param name="repo">yegor256/xcop</param>
      <param name="issue">20</param>
      <param name="comment">386854470</param>
   </params>
   <token>github;yegor256/xcop;20;386854470</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/xcop#20, Comment: 386854470

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/xcop/issues/20#issuecomment-386854470))

@yegor256 The job [#20](https://github.com/yegor256/xcop/issues/20) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3RFVLU72/1260544456); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/xcop/issues/20#issuecomment-386854470))

@yegor256 Job `gh:yegor256/xcop#20` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
