### ISSUE TITLE
Configuration file for xcop

### ISSUE THREAD

**Issue by llorllale** [yegor256/xcop#24]
Let's add ability to configure xcop via an `.xcop` file. The default behavior for xcop should be to look for this file in the current directory. 

(this is a continuation of [this](https://github.com/jcabi/jcabi-parent/issues/79#issuecomment-376567936) discussion)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale would you be interested in contributing a pull request? Similar to this one: https://github.com/yegor256/pdd/blob/master/bin/pdd#L32-L40

**Comment by llorllale** [comment]
@yegor256 I have never touched ruby code but I will give it a shot

**Comment by yegor256** [comment]
@llorllale should be super easy, just a few lines of code

**Comment by llorllale** [comment]
Fixed in #27

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/xcop#24` is not assigned, can't get performer
