### ISSUE TITLE
`--fix` for all files in directory

### ISSUE THREAD

**Issue by MikhailLipanin** [yegor256/xcop#37]
@yegor256, can you check, does it (`$ xcop --fix $(find . -name '*.xml')`) works well?
In my case, it didn't work and I have applied `xcop` directly to each file in directory.
My directory:
![image](https://user-images.githubusercontent.com/95661085/201347566-02095a0f-649c-43a2-802e-ef3f6fcfcc51.png)

May be it is required to add additional Junit-tests.

Also, it would be great if we can apply `xcop` for directories tree --- i.e. for XML-files that occurs not only in current directory, but also in directories inside of the current.

**Comment by yegor256** [comment]
@MikhailLipanin you need to do (because you have `xsl` files too):

```
$ xcop --fix $(find . -name '*.xml' -name '*.xsl')
```

**Comment by 0crat** [comment]
Job `gh:yegor256/xcop#37` is not assigned, can't get performer
